
telegram:
  bot:
    token1: ${TELEGRAM_TOKEN1}
    id1: ${TELEGRAM_ID1}

    token2: ${TELEGRAM_TOKEN2}
    id2: ${TELEGRAM_ID2}

    token3: ${TELEGRAM_TOKEN3}
    id3: ${TELEGRAM_ID3}

spring:
  application:
    name: "gradesbot-git-alert"
  profiles:
    active: dev
server:
  port: 8080